baseURL = "https://nutriwisepnh1.netlify.app"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
themesDir = "../.."
title = "Nutriwise"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.main]]
name = "services"
url = "#services"
weight = 2
stripeColor = "#3D78BC"
[[Languages.en.menu.main]]
name = "blg"
url = "#blog"
weight = 6
stripeColor = "#3D78BC"
[[Languages.en.menu.main]]
name = "contact"
url = "#contact"
weight = 7
stripeColor = "#3D78BC"
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[Languages.fr.menu.main]]
name = "sur"
url = "#about"
weight = 1
[[Languages.fr.menu.main]]
name = "un service"
url = "#services"
weight = 2
[[Languages.fr.menu.main]]
name = "blog"
url = "#blog"
weight = 6
[[Languages.fr.menu.main]]
name = "contact"
url = "#contact"
weight = 7
[params]
author = "Melanie van Gendt"
description = ""
google_analytics_id = "nutriwise.pnh"
logo = "images/nutriwise_v1.png"
post_share = true
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "11.540541"
map_longitude = "104.915957"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "images/websitelogo_v2.png"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-instagram"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
